# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'server1'
    static_configs:
      - targets: ['server1:3721']

  - job_name: 'server2'
    static_configs:
      - targets: ['server2:3722']

  - job_name: 'server3'
    static_configs:
      - targets: ['server2:3723']

  - job_name: 'server4'
    static_configs:
      - targets: ['server4:3724']

  - job_name: 'server5'
    static_configs:
      - targets: ['server5:3725']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

